# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtctl" do
  version "0.36.0"

  on_macos do
    on_intel do
      sha256 "a892941792d9a61467515d6ae3d6681ee8f2c29632c0f23db5059f0c88ec0dc9"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "52936fbbdd6c0a57960f4b16c35708f729a88c6fae36861698335d52959c8c04"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3027bde2496f634aa22144f916c1fab3f0a44f18bec85089e5b71ca498f96b31"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "280e42da7f58539bf48f67514949a7bc4c90f3e6745b6acfe8db64f7f0396182"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dtctl"
  desc "kubectl-inspired CLI for Dynatrace - manage workflows, dashboards, SLOs, queries, and more from your terminal"
  homepage "https://github.com/dynatrace-oss/dtctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtctl"
  bash_completion "completions/dtctl.bash"
  fish_completion "completions/dtctl.fish"
  zsh_completion "completions/dtctl.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"]
    end
  end

  # No zap stanza required

end
