# typed: strict
# frozen_string_literal: true

# Opt-in prerelease channel for dtctl. Hand-maintained (NOT generated by
# GoReleaser): tracks the latest dtctl prerelease so users can subscribe to
# bleeding-edge builds without affecting the stable `dtctl` cask.
#
#   brew install dynatrace-oss/tap/dtctl@beta
#
cask "dtctl@beta" do
  version "0.32.0-rc.3"

  on_macos do
    on_intel do
      sha256 "c8867765319b2fe80e503f8af02d67ffc591631a70124e9d8dc3e416ce341b79"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d3d2446890fb8aa07dbae02182895b55b910ecfc562cb8e368cd33c59728d8b"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e64f0abd313596e8a54642d9e992458a4be6d765cd6c021f1d30c6be70cfc0ad"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7356b869b8a14edf19cdae7c52b6f2f39f3d1850e4222d61089a9326ffda6cc0"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dtctl (prerelease)"
  desc "Prerelease channel of dtctl - kubectl-inspired CLI for Dynatrace"
  homepage "https://github.com/dynatrace-oss/dtctl"

  livecheck do
    skip "Prerelease channel, updated manually."
  end

  # Both casks install a `dtctl` binary; keep them mutually exclusive.
  conflicts_with cask: "dynatrace-oss/tap/dtctl"

  binary "dtctl"
  bash_completion "completions/dtctl.bash"
  fish_completion "completions/dtctl.fish"
  zsh_completion "completions/dtctl.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"] if OS.mac?
  end

  # No zap stanza required
end
