# typed: strict
# frozen_string_literal: true

# Opt-in prerelease channel for dtctl. Hand-maintained (NOT generated by
# GoReleaser): tracks the latest dtctl prerelease so users can subscribe to
# bleeding-edge builds without affecting the stable `dtctl` cask.
#
#   brew install dynatrace-oss/tap/dtctl@beta
#
cask "dtctl@beta" do
  version "0.32.0-rc.2"

  on_macos do
    on_intel do
      sha256 "d01f196a358d590f1648b2a68590621a3f5c2c08baba40dba707b0ab702d7df2"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a573aeabf2979d7d7e8d8b7088340fd383f36d48ce2d55697cc990a483e5490"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0a291606a07671055787703aea277329f0d765ebd48784c9497ae6e67815811"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "def841aa73df0a878ca4fd412f9fbdecbbf26ceaeab02cf721f6f84452d0d131"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dtctl (prerelease)"
  desc "Prerelease channel of dtctl - kubectl-inspired CLI for Dynatrace"
  homepage "https://github.com/dynatrace-oss/dtctl"

  livecheck do
    skip "Prerelease channel, updated manually."
  end

  # Both casks install a `dtctl` binary; keep them mutually exclusive.
  conflicts_with cask: "dynatrace-oss/tap/dtctl"

  binary "dtctl"
  bash_completion "completions/dtctl.bash"
  fish_completion "completions/dtctl.fish"
  zsh_completion "completions/dtctl.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"] if OS.mac?
  end

  # No zap stanza required
end
