# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtctl" do
  name "dtctl"
  desc "kubectl-inspired CLI for Dynatrace - manage workflows, dashboards, SLOs, queries, and more from your terminal"
  homepage "https://github.com/dynatrace-oss/dtctl"
  version "0.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtctl"
  bash_completion "completions/dtctl.bash"
  zsh_completion "completions/dtctl.zsh"
  fish_completion "completions/dtctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_amd64.tar.gz"
      sha256 "f46bf36b6cb8b7a7195f6bb52aeec2f3e0957a5ac14156b56e7e5d436dddeead"
    end
    on_arm do
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_arm64.tar.gz"
      sha256 "b5c2fe2dbe75d74208d9ad91d80a40000bb1f517a47b5948b1fa728caaab22d7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_amd64.tar.gz"
      sha256 "cc0d7c40daa19f3484efd99c100b99f5ebe476ff26c8866227da9afffb42ad4c"
    end
    on_arm do
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_arm64.tar.gz"
      sha256 "ae45f37e37b7cf6283a2754d414c852613d76421433aa4c189ce8d240c6a2872"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"]
    end
  end

  # No zap stanza required
end
