# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtctl" do
  name "dtctl"
  desc "kubectl-inspired CLI for Dynatrace - manage workflows, dashboards, SLOs, queries, and more from your terminal"
  homepage "https://github.com/dynatrace-oss/dtctl"
  version "0.14.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtctl"
  bash_completion "completions/dtctl.bash"
  zsh_completion "completions/dtctl.zsh"
  fish_completion "completions/dtctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_amd64.tar.gz"
      sha256 "1c6ea51a1d0d1ee7c42f158379f7b21d2dee7d0be750acf1fd1752538639a2cd"
    end
    on_arm do
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_arm64.tar.gz"
      sha256 "1ff5d36839b25f224a976130ad3264143e9e15067340fd4c151c1820a29921bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_amd64.tar.gz"
      sha256 "0dcef504516ab84a2e00ed6a4db32b41bcb5e3ade47e5679a54d7b7c14dfa66a"
    end
    on_arm do
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_arm64.tar.gz"
      sha256 "6e4e9ee85a92747b52ec3970d796ce30cfde0ddd3f4361528eaa4ffaee546908"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"]
    end
  end

  # No zap stanza required
end
