# typed: strict
# frozen_string_literal: true

# Opt-in prerelease channel for dtctl. Hand-maintained (NOT generated by
# GoReleaser): tracks the latest dtctl prerelease so users can subscribe to
# bleeding-edge builds without affecting the stable `dtctl` cask.
#
#   brew install dynatrace-oss/tap/dtctl@beta
#
cask "dtctl@beta" do
  version "0.32.0-rc.1"

  on_macos do
    on_intel do
      sha256 "ba3f0be020bb2d0be2c686205dbabcd2a922e9f103a56d196dd5d1e18802d93d"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "89c1b0c42dcad4db7c85dcb03019016b472657b90f22687bc8ce60adc695bb45"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e4badf4df66f3f766b173eb97693860d70dd550cbf8a36f397fe38ced3fdbcc"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3a411c6f7404d4312b29d19fbb7a088c2433c456c0de113cd05d00b13a07e20"
      url "https://github.com/dynatrace-oss/dtctl/releases/download/v#{version}/dtctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dtctl (prerelease)"
  desc "Prerelease channel of dtctl - kubectl-inspired CLI for Dynatrace"
  homepage "https://github.com/dynatrace-oss/dtctl"

  livecheck do
    skip "Prerelease channel, updated manually."
  end

  # Both casks install a `dtctl` binary; keep them mutually exclusive.
  conflicts_with cask: "dynatrace-oss/tap/dtctl"

  binary "dtctl"
  bash_completion "completions/dtctl.bash"
  fish_completion "completions/dtctl.fish"
  zsh_completion "completions/dtctl.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"] if OS.mac?
  end

  # No zap stanza required
end
