# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtmgd" do
  version "0.0.27"

  on_macos do
    on_intel do
      sha256 "38a73f8f59ee88ce5267e757c3367c9b9b7f63e1035a9151ef946e12b87424ea"
      url "https://github.com/dynatrace-oss/dtmgd/releases/download/v#{version}/dtmgd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "758462aa9f2bf656929dc3cf5fcc82604ea54b21064741486e402a5577f66f1e"
      url "https://github.com/dynatrace-oss/dtmgd/releases/download/v#{version}/dtmgd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce80c335a1390da6a76ce4927f2a42c6d4e1013b442d149ab4c04d5e92b1c2bb"
      url "https://github.com/dynatrace-oss/dtmgd/releases/download/v#{version}/dtmgd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f120cdf83ce1415fde85353a32ccb8132188b409bc6d6aa14d237c3670eeabef"
      url "https://github.com/dynatrace-oss/dtmgd/releases/download/v#{version}/dtmgd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dtmgd"
  desc "kubectl-inspired CLI for Dynatrace Managed - problems, entities, events, logs, metrics, SLOs, and security from your terminal"
  homepage "https://github.com/dynatrace-oss/dtmgd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtmgd"
  bash_completion "completions/dtmgd.bash"
  fish_completion "completions/dtmgd.fish"
  zsh_completion "completions/dtmgd.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtmgd"]
    end
  end

  # No zap stanza required

end
