# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtmgd" do
  version "0.0.28"

  on_macos do
    on_intel do
      sha256 "6165d30620eb259f8d13ab8898b0dbba08af14da2b62670263663b9e30c8470b"
      url "https://github.com/dynatrace-oss/dtmgd/releases/download/v#{version}/dtmgd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "baab0cbfeb1cc4405aff8e691af3587d76b21af0ba1124c7e865e53227430422"
      url "https://github.com/dynatrace-oss/dtmgd/releases/download/v#{version}/dtmgd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8a64190af26528ab1b3a50226b289813616d8428af5cb3f72cf128339836849d"
      url "https://github.com/dynatrace-oss/dtmgd/releases/download/v#{version}/dtmgd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d4944fbb848a91b495b204db752278ec1b42e8e64619b9d12fb5127070c359c"
      url "https://github.com/dynatrace-oss/dtmgd/releases/download/v#{version}/dtmgd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dtmgd"
  desc "kubectl-inspired CLI for Dynatrace Managed - problems, entities, events, logs, metrics, SLOs, and security from your terminal"
  homepage "https://github.com/dynatrace-oss/dtmgd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtmgd"
  bash_completion "completions/dtmgd.bash"
  fish_completion "completions/dtmgd.fish"
  zsh_completion "completions/dtmgd.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtmgd"]
    end
  end

  # No zap stanza required

end
